# Generated by Django 2.1.5 on 2019-01-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoMateriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('condicao', models.CharField(max_length=10)),
                ('observacoes', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
