# Generated by Django 2.1.4 on 2018-12-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruds', '0005_requisitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('dataRecebimento', models.DateField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('observacoes', models.TextField()),
                ('idFornecedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cruds.Fornecedor')),
            ],
        ),
    ]
