# Generated by Django 2.1.4 on 2018-12-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcaoMateriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('notaFiscal', models.CharField(max_length=50)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idPedidoCompra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.PedidoCompra')),
            ],
        ),
    ]
