# Generated by Django 2.1.4 on 2018-12-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_retiradasmateriais'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoMateriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('horaRegistro', models.TimeField()),
                ('situacao', models.CharField(max_length=10)),
                ('observacoes', models.TextField()),
                ('idRetiradasMateriais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.RetiradasMateriais')),
            ],
        ),
    ]
