# Generated by Django 2.1.4 on 2018-12-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_auto_20181223_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('consumivel', models.CharField(max_length=10)),
                ('observacoes', models.TextField()),
                ('estoqueMinimo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estoqueMaximo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estoqueAtual', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiais_imagens')),
                ('idCategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Categoria')),
                ('idUnidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Unidade')),
            ],
        ),
    ]
