# Generated by Django 2.1.4 on 2018-12-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiais_imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiais_imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiais_imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiais_imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiais_imagens')),
            ],
        ),
    ]
