# Generated by Django 2.1.4 on 2018-12-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Requisitante',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
