# Generated by Django 2.1.4 on 2018-12-23 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiais', '0004_material'),
        ('registros', '0005_devolucaomateriais'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idDevolucaoMateriais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.DevolucaoMateriais')),
                ('idMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Material')),
            ],
        ),
        migrations.CreateModel(
            name='itemPedidoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Material')),
                ('idPedidoCompra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.PedidoCompra')),
            ],
        ),
        migrations.CreateModel(
            name='itemRecepcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Material')),
                ('idRececaoMateriais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.RecepcaoMateriais')),
            ],
        ),
        migrations.CreateModel(
            name='itemRequisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Material')),
                ('idRequisicaoMateriais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.RequisicaoMateriais')),
            ],
        ),
        migrations.CreateModel(
            name='itemRetirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.Material')),
                ('idRetiradasMateriais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.RetiradasMateriais')),
            ],
        ),
    ]
